version: '3.3'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'vadik'
      MYSQL_USER: 'vadikUser'
      MYSQL_PASSWORD: 'vadikPassword'
      MYSQL_ROOT_PASSWORD: 'roto'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
